import json
from multiway_trade_builder.build_multiway_trade import build_multiway_trade

# Using Library function!

contract_file = input("SAVE file as? [.clar] : ")

newContract = open("autoGeneratedContracts\%s.clar"%(contract_file), "w", newline='\n')

jsonFile = open("example.json", "r")
inputs = jsonFile.read()
# print(inputs)
contract_details = json.loads(inputs)

# Library
CODE = build_multiway_trade(contract_details)

newContract.write(CODE)

jsonFile.close()
newContract.close()